### ISSUE TITLE
Extension occurs an error

### ISSUE THREAD

**Issue by ByPikod** [alphaxek/github-actions-locally#3]
# Issue

VSCode occurs an error as I opened the **Github Actions Locally** using CTRL + SHIFT + P. I've put the logs below that might be related to the issue.

![resim](https://github.com/alphaxek/github-actions-locally/assets/46069238/68fc5c3d-ba4b-4063-98c0-d609a5435402)

## Extension Host logs

```2023-12-20 16:33:16.746 [error] TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at c:\Users\yahya\.vscode\extensions\alphaxek.github-actions-locally-0.0.7\extension.js:151:13
    at d.h (c:\Users\yahya\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:141:140094)
    at d.$executeContributedCommand (c:\Users\yahya\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:141:140954)
    at l.S (c:\Users\yahya\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:150:10829)
    at l.Q (c:\Users\yahya\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:150:10595)
    at l.M (c:\Users\yahya\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:150:9685)
    at l.L (c:\Users\yahya\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:150:8764)
    at f.value (c:\Users\yahya\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:150:7567)
    at n.y (c:\Users\yahya\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:80:1902)
    at n.fire (c:\Users\yahya\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:80:2119)
    at o.fire (c:\Users\yahya\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:103:14039)
    at f.value (c:\Users\yahya\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:171:7903)
    at n.y (c:\Users\yahya\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:80:1902)
    at n.fire (c:\Users\yahya\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:80:2119)
    at o.fire (c:\Users\yahya\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:103:14039)
    at MessagePortMain.<anonymous> (c:\Users\yahya\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:171:6183)
    at MessagePortMain.emit (node:events:513:28)
    at Object.MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:367) github-actions-locally.gal {"value":"alphaxek.github-actions-locally","_lower":"alphaxek.github-actions-locally"}
```

## Shared console logs

```
2023-12-20 16:32:12.053 [info] Getting Manifest... alphaxek.github-actions-locally
2023-12-20 16:32:12.059 [info] Installing extension: alphaxek.github-actions-locally
2023-12-20 16:32:26.074 [info] Extension signature is verified: alphaxek.github-actions-locally
2023-12-20 16:32:27.838 [info] Extracted extension to file:///c%3A/Users/yahya/.vscode/extensions/alphaxek.github-actions-locally-0.0.7: alphaxek.github-actions-locally
2023-12-20 16:32:27.853 [info] Renamed to c:\Users\yahya\.vscode\extensions\alphaxek.github-actions-locally-0.0.7
2023-12-20 16:32:27.862 [info] Extracting extension completed. alphaxek.github-actions-locally
2023-12-20 16:32:27.877 [info] Extension installed successfully: alphaxek.github-actions-locally
2023-12-20 16:32:27.972 [error] [uncaught exception in sharedProcess]: Error: ENOENT: no such file or directory, stat 'c:\Users\yahya\.vscode\extensions\extensions.json.vsctmp': EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, stat 'c:\Users\yahya\.vscode\extensions\extensions.json.vsctmp'
    at r.create (c:\Users\yahya\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:51:30056)
    at a (c:\Users\yahya\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:51:30170)
    at s.fb (c:\Users\yahya\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:56:36175)
    at s.stat (c:\Users\yahya\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:56:28621)
    at async E.stat (c:\Users\yahya\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:56:15732)
    at async Y.tb (c:\Users\yahya\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:100:111319)
```

## Window console logs

```
2023-12-20 16:36:43.378 [error] There are no commenting ranges at the current position.: Error: There are no commenting ranges at the current position.
    at O.addCommentAtLine (vscode-file://vscode-app/c:/Users/yahya/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2063:2555)
    at O.addOrToggleCommentAtLine (vscode-file://vscode-app/c:/Users/yahya/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2063:2087)
    at O.Y (vscode-file://vscode-app/c:/Users/yahya/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2063:1793)
    at o.value (vscode-file://vscode-app/c:/Users/yahya/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2062:18489)
    at J.y (vscode-file://vscode-app/c:/Users/yahya/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:87:1902)
    at J.z (vscode-file://vscode-app/c:/Users/yahya/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:87:1972)
    at J.fire (vscode-file://vscode-app/c:/Users/yahya/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:87:2188)
    at J.fire (vscode-file://vscode-app/c:/Users/yahya/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:744:19871)
    at Vb.he.onMouseUp (vscode-file://vscode-app/c:/Users/yahya/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:744:18171)
    at S.emitMouseUp (vscode-file://vscode-app/c:/Users/yahya/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:95:39512)
    at D.emitMouseUp (vscode-file://vscode-app/c:/Users/yahya/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:681:40889)
    at g.F (vscode-file://vscode-app/c:/Users/yahya/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:719:14420)
    at vscode-file://vscode-app/c:/Users/yahya/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:719:12058
    at HTMLDivElement.<anonymous> (vscode-file://vscode-app/c:/Users/yahya/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:714:30685)
```

**Comment by alphaxek** [comment]
Hi @ByPikod , thanks for reaching out, can you please confirm if you have docker & Nektos/act installed globally in your system and your operating system please.

Thanks for trying my extensions but please note this is under dev and not stable in every environments, I would love some PRs from you if you would like to contribute to this extension in your free time, Thanks!!!

**Comment by dorz-saymine** [comment]
Same issue for me, using mac m3

**Comment by alphaxek** [comment]
Hi @dorz-saymine , thanks for reaching out, can you please confirm if you have docker & Nektos/act installed globally in your system.

**Comment by dorz-saymine** [comment]
> Hi @dorz-saymine , thanks for reaching out, can you please confirm if you have docker & Nektos/act installed globally in your system.

Yes docker and Nektos/act is installed locally and was able to run workflows via act cli

**Comment by alphaxek** [comment]
Hi @dorz-saymine, thank you so much for the info, can you please also confirm the OS to improve my code, meanwhile let me have a look and get back to you.

**Please star my repo, I will really appreciate your efforts, thank you.**

**Comment by dorz-saymine** [comment]
> Hi @dorz-saymine, thank you so much for the info, can you please also confirm the OS to improve my code, meanwhile let me have a look and get back to you.
> 
> **Please star my repo, I will really appreciate your efforts, thank you.**

MacOS 14.2.1 (23C71) - Chip Apple M3 Pro

**Comment by alphaxek** [comment]
Hi @dorz-saymine , thank you so much for starring my repo and for the above info.

Currently the extension is still in idea phase so it only supports Windows, I will work on it to support other OS as well.
Till then I can enhance error handling to tell if it supports OS or not, thank you for your input I really appreciate.

**Comment by rydupra** [comment]
![Screenshot 2024-08-30 190249](https://github.com/user-attachments/assets/ced25b38-de14-45f1-96cd-1391e54807ad)
Already install Docker Desktop and Nektos/act
I am using windows 11 64 bit

VS Code Version: 1.92.2 (user setup)
Commit: fee1edb8d6d72a0ddff41e5f71a671c23ed924b9
Date: 2024-08-14T17:29:30.058Z
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.22631

**I already stars your repo**
